### ISSUE TITLE
RuntimeError: DataLoader worker (pid 31703) is killed by signal: Terminated. 

### ISSUE THREAD

**Issue by ronghui19** [NVlabs/stylegan2-ada-pytorch#10]
Traceback (most recent call last):
  File "train.py", line 530, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/osm/torchgan/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/osm/torchgan/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/osm/torchgan/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/osm/torchgan/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/osm/torchgan/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 523, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 376, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/home/osm/stylegan2-ada-pytorch-main/training/training_loop.py", line 147, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/home/osm/stylegan2-ada-pytorch-main/dnnlib/util.py", line 289, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/home/osm/stylegan2-ada-pytorch-main/dnnlib/util.py", line 284, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/home/osm/stylegan2-ada-pytorch-main/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/home/osm/stylegan2-ada-pytorch-main/training/networks.py", line 493, in __init__
    self.synthesis = SynthesisNetwork(w_dim=w_dim, img_resolution=img_resolution, img_channels=img_channels, **synthesis_kwargs)
  File "/home/osm/stylegan2-ada-pytorch-main/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/home/osm/stylegan2-ada-pytorch-main/training/networks.py", line 434, in __init__
    assert img_resolution >= 4 and img_resolution & (img_resolution - 1) == 0
AssertionError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/osm/torchgan/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 31703) is killed by signal: Terminated.

**Comment by ronghui19** [comment]
i set workers = 0. It still happens

**Comment by ronghui19** [comment]
never mind. input should be same. Ex: (256, 256, 3)
