### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by loctruong96** [NVlabs/stylegan2-ada-pytorch#103]
Running on a slurm cluster. The following environment variables and modules were set:
module load cuda/11.0
export CUDA_HOME=/share/apps/cuda/11.0/

Happen when try running 
python train.py --outdir=./training-runs --data=./datasets/cifar10.zip --gpus=1 
or
python generate.py --outdir=out --trunc=1 --seeds=85,265,297,849 \
    --network=https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metfaces.pkl

Error: 
Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.

Generator            Parameters  Buffers  Output shape       Datatype
---                  ---         ---      ---                ---
mapping.fc0          262656      -        [32, 512]          float32
mapping.fc1          262656      -        [32, 512]          float32
mapping              -           512      [32, 8, 512]       float32
synthesis.b4.conv1   2622465     32       [32, 512, 4, 4]    float32
synthesis.b4.torgb   264195      -        [32, 3, 4, 4]      float32
synthesis.b4:0       8192        16       [32, 512, 4, 4]    float32
synthesis.b4:1       -           -        [32, 512, 4, 4]    float32
synthesis.b8.conv0   2622465     80       [32, 512, 8, 8]    float16
synthesis.b8.conv1   2622465     80       [32, 512, 8, 8]    float16
synthesis.b8.torgb   264195      -        [32, 3, 8, 8]      float16
synthesis.b8:0       -           16       [32, 512, 8, 8]    float16
synthesis.b8:1       -           -        [32, 512, 8, 8]    float32
synthesis.b16.conv0  2622465     272      [32, 512, 16, 16]  float16
synthesis.b16.conv1  2622465     272      [32, 512, 16, 16]  float16
synthesis.b16.torgb  264195      -        [32, 3, 16, 16]    float16
synthesis.b16:0      -           16       [32, 512, 16, 16]  float16
synthesis.b16:1      -           -        [32, 512, 16, 16]  float32
synthesis.b32.conv0  2622465     1040     [32, 512, 32, 32]  float16
synthesis.b32.conv1  2622465     1040     [32, 512, 32, 32]  float16
synthesis.b32.torgb  264195      -        [32, 3, 32, 32]    float16
synthesis.b32:0      -           16       [32, 512, 32, 32]  float16
synthesis.b32:1      -           -        [32, 512, 32, 32]  float32
---                  ---         ---      ---                ---
Total                19947539    3392     -                  -

Discriminator  Parameters  Buffers  Output shape       Datatype
---            ---         ---      ---                ---
b32.fromrgb    2048        16       [32, 512, 32, 32]  float16
b32.skip       262144      16       [32, 512, 16, 16]  float16
b32.conv0      2359808     16       [32, 512, 32, 32]  float16
b32.conv1      2359808     16       [32, 512, 16, 16]  float16
b32            -           16       [32, 512, 16, 16]  float16
b16.skip       262144      16       [32, 512, 8, 8]    float16
b16.conv0      2359808     16       [32, 512, 16, 16]  float16
b16.conv1      2359808     16       [32, 512, 8, 8]    float16
b16            -           16       [32, 512, 8, 8]    float16
b8.skip        262144      16       [32, 512, 4, 4]    float16
b8.conv0       2359808     16       [32, 512, 8, 8]    float16
b8.conv1       2359808     16       [32, 512, 4, 4]    float16
b8             -           16       [32, 512, 4, 4]    float16
b4.mbstd       -           -        [32, 513, 4, 4]    float32
b4.conv        2364416     16       [32, 512, 4, 4]    float32
b4.fc          4194816     -        [32, 512]          float32
b4.out         513         -        [32, 1]            float32
---            ---         ---      ---                ---
Total          21507073    224      -                  -

Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
Initializing logs...
Skipping tfevents export: No module named 'tensorboard'
Training for 25000 kimg...

Traceback (most recent call last):
  File "train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/qfs/projects/BandonDunes/workspace/loc/stylegan2-ada-pytorch/training/training_loop.py", line 284, in training_loop
    loss.accumulate_gradients(phase=phase.name, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, sync=sync, gain=gain)
  File "/qfs/projects/BandonDunes/workspace/loc/stylegan2-ada-pytorch/training/loss.py", line 74, in accumulate_gradients
    loss_Gmain.mean().mul(gain).backward()
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/qfs/projects/BandonDunes/workspace/loc/anaconda3/envs/tonga_stylegan/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/qfs/projects/BandonDunes/workspace/loc/stylegan2-ada-pytorch/torch_utils/ops/conv2d_gradfix.py", line 131, in backward
    grad_weight = Conv2dGradWeight.apply(grad_output, input)
  File "/qfs/projects/BandonDunes/workspace/loc/stylegan2-ada-pytorch/torch_utils/ops/conv2d_gradfix.py", line 145, in forward
    grad_weight = op(weight_shape, grad_output, input, padding, stride, dilation, groups, *flags)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = False
data = torch.randn([32, 512, 16, 16], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 512, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = false
input: TensorDescriptor 0x2b51400548e0
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 32, 512, 16, 16,
    strideA = 131072, 256, 16, 1,
output: TensorDescriptor 0x2b51400bbf60
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 32, 512, 16, 16,
    strideA = 131072, 256, 16, 1,
weight: FilterDescriptor 0x2b514005d120
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 512, 512, 3, 3,
Pointer addresses:
    input: 0x2b51c3888000
    output: 0x2b51c4d08000
    weight: 0x2b51cc690000

Segmentation fault (core dumped)

**Desktop (please complete the following information):**
 - OS: CentOS-7
 - PyTorch version 1.7.1
 - CUDA toolkit version: CUDA 11
 - NVIDIA driver version 455.32.00
 - GPU: Tesla P100
 - Docker: No. Not allowed by cluster.

**Comment by kc-puttagunta** [comment]
@loctruong96 did you find a solution to this issue? Please share, if you did! thanks

**Comment by loctruong96** [comment]
> @loctruong96 did you find a solution to this issue? Please share, if you did! thanks

No. I couldn't figure out how to fix this issue so I get around it by using docker.

**Comment by kc-puttagunta** [comment]
> > @loctruong96 did you find a solution to this issue? Please share, if you did! thanks
> 
> No. I couldn't figure out how to fix this issue so I get around it by using docker.

Okay. I was able to get it running by downgrading PyTorch to 1.8.1 from 1.9. Didn't encounter seg fault error this way. Try if this works for you

**Comment by Mo-Irene** [comment]
I also encountered the same problem, if anyone knows how to solve it, please give me some suggestions, I will be grateful.
