### ISSUE TITLE
RuntimeError: CUDA out of memory. Even though I have enough

### ISSUE THREAD

**Issue by siriusIX** [NVlabs/stylegan2-ada-pytorch#125]
I am very new to this. I tried running train.py in anaconda and the image preparation worked fine and then when I run the actual training command it shows this error message (the first picture) saying it is out of memory even though I clearly have enough. I am trying to train a 25 image dataset (I went small because I thought it was a memory issue) and see results. The "bias_act_plugin" and "upfirdn2d_plugin" are working. I am using python 3.7.9 but the paths show up differently in visual studio code. I don't know if that affects it (that's the second image in screenshots) I've seen people talk about clearing the cache and changing the batch size but I do not know how to do that. The image sizes are 256 resolution. 
**To Reproduce**
run train.py in anaconda PS prompt (please ask me more details about what I did so I can be as descriptive as possible)

See error 

`RuntimeError: CUDA out of memory. Tried to allocate 9.07 GiB (GPU 0; 24.00 GiB total capacity; 594.67 MiB already allocated; 12.43 GiB free; 9.21 GiB reserved in total by PyTorch)`

**Expected behavior**
The train results to appear in my folder labeled "trainResults"

**Screenshots**
![Screenshot 2021-06-13 200107](https://user-images.githubusercontent.com/75517887/121827591-3ca20d00-cc82-11eb-81df-6081c15b0922.jpg)

![Screenshot 2021-06-13 200307](https://user-images.githubusercontent.com/75517887/121827667-7d9a2180-cc82-11eb-8747-e0e026c0f26e.jpg)

![Screenshot 2021-06-13 200739](https://user-images.githubusercontent.com/75517887/121827794-12048400-cc83-11eb-8620-3cd2882aead1.jpg)

**Desktop**
 - OS: Windows 10
 - PyTorch version : pytorch 1.7.1
 - CUDA toolkit version : 11.3
 - NVIDIA driver version: 466.77
 - GPU : RTX 3090
 - Docker: did you use Docker? No

**Additional context**
If I made any obvious mistakes please let me know like I said I am very new to this.

**Comment by hkhailee** [comment]
I was having the same issues only mine was actually out of memory. Fixing it I just moved to use the docker file they provided with some modifications in building and running. 

docker build --tag sg2ada:latest --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) .

docker run --shm-size=2g --gpus all -it --rm -v `pwd`:/scratch --workdir=/scratch -e HOME=/scratch sg2ada:latest bash

Then I was working directly in docker with the proper setup no cuda memory issues. If anyone has an alternate solution to this it would be super helpful,  personally I spent a few days exploring the issue and couldn't figure out how to fix it even with garbage collections being added in scripts.

**Comment by siriusIX** [comment]
Can you explain how to make these modifications and what the arguments mean (sorry I am also new to docker).

**Comment by Macaque2077** [comment]
I'm on an A100 with 39gb of memory and running out of memory with a batch size of 8, though a batch size of 4 works. Images are 256x256 and theres 8,000 of them. is this normal or is there a solution?

**Comment by orgicus** [comment]
I'm experiencing a similar issue:

```
Constructing networks...
Traceback (most recent call last):
  File "train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "D:\gp\ml\tgpu\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\gp\ml\tgpu\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\gp\ml\tgpu\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\gp\ml\tgpu\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\gp\ml\tgpu\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "D:\gp\ml\stylegan2-ada-pytorch\training\training_loop.py", line 150, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "D:\gp\ml\tgpu\lib\site-packages\torch\nn\modules\module.py", line 612, in to
    return self._apply(convert)
  File "D:\gp\ml\tgpu\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "D:\gp\ml\tgpu\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "D:\gp\ml\tgpu\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "D:\gp\ml\tgpu\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
    param_applied = fn(param)
  File "D:\gp\ml\tgpu\lib\site-packages\torch\nn\modules\module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 22.50 GiB total capacity; 1.00 MiB already allocated; 18.54 GiB free; 2.00 MiB reserved in total by PyTorch)
```

**Desktop**

- OS: Windows 10
- PyTorch version : pytorch 1.7.1
- CUDA toolkit version : 11.1
- NVIDIA driver version: 461.92
- GPU : RTX 3090
- Docker: did you use Docker? No

Any suggestions what else we could try ?

Thank you so much !
