### ISSUE TITLE
'object has no attribute '_workers_status'

### ISSUE THREAD

**Issue by Muwusiz** [NVlabs/stylegan2-ada-pytorch#132]
**Describe the bug**
when evaluating metrics dataloader.py throws error

**To Reproduce**
1. In main stylegan 2 directory run 

> py train.py --data D:\source\code\machine-learning\datasets\chess --outdir D:\source\code\machine-learning\results\chess --batch 16 --kimg 1000

2. Wait for metric evaluation to start, See error: 

> Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x00000250FF90A950>
Traceback (most recent call last):
  File "C:\Users\Lynne\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "C:\Users\Lynne\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'

**Expected behavior**

> stylegan2 continues ahead after evaluating metrics

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PyTorch version: 1.7.1+cu110
 - CUDA toolkit version: CUDA 11.1
 - NVIDIA driver version: 466.77
 - GPU: Nvidia RTX 3070M
 - Docker: did you use Docker?  no

**Comment by manoadamro** [comment]
@Muwusiz I had to use CUDA 11.4 to get it working on a 30xx card

got it all working properly with:

OS: Windows 10
PyTorch version: py3.7_cuda11.1_cudnn8_0
CUDA toolkit version: CUDA 11.4
NVIDIA driver version: 471.41
GPU: Nvidia RTX 3090

(I did install pytorch using conda)
hope that helps
