### ISSUE TITLE
UserWarning: Failed to build CUDA kernels for bias_act

### ISSUE THREAD

**Issue by dokluch** [NVlabs/stylegan2-ada-pytorch#142]
**Describe the bug**
I am trying to set up stylegan2-ada-pytorch to work on a new Windows machine, and I am pretty sure I've checked through all prerequisites:
-MS Visual Studio 2019, added to path
-Cuda toolkit 11.4
-conda installed the same env as on another machine (python 3.7, torch 1.7.1 etc)

but I am getting now issues with bias_act plugin

**To Reproduce**
1. Any stylegan interaciton

Please copy&paste text instead of screenshots for better searchability.

```
D:\ArtGAN\CLIP\stylegan2-ada-pytorch\torch_utils\ops\bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "C:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "C:\Users\usrname\.conda\envs\stylegan-clip\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ArtGAN\CLIP\stylegan2-ada-pytorch\torch_utils\ops\bias_act.py", line 48, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "D:\ArtGAN\CLIP\stylegan2-ada-pytorch\torch_utils\custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "C:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\utils\cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\utils\cpp_extension.py", line 1300, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "C:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/3] C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.3\bin\nvcc -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include\TH -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include\THC "-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.3\include" -IC:\Users\usrname\.conda\envs\stylegan-clip\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 --use_fast_math -c D:\ArtGAN\CLIP\stylegan2-ada-pytorch\torch_utils\ops\bias_act.cu -o bias_act.cuda.o 
FAILED: bias_act.cuda.o 
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.3\bin\nvcc -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include\TH -IC:\Users\usrname\.conda\envs\stylegan-clip\lib\site-packages\torch\include\THC "-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.3\include" -IC:\Users\usrname\.conda\envs\stylegan-clip\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 --use_fast_math -c D:\ArtGAN\CLIP\stylegan2-ada-pytorch\torch_utils\ops\bias_act.cu -o bias_act.cuda.o 
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid.



  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
```

**Desktop (please complete the following information):**
 - Windows 10
 - PyTorch 1.7.1
 - CUDA toolkit 11.4
 - NVIDIA driver version 471.11
 - GPU GeForce RTX A6000
 - Docker: no

**Additional context**

**Comment by dokluch** [comment]
Upon thoroughly reading the error message, I've discovered a weird CUDA versions mismatch, so I've reinstalled GPU driver along with CUDA toolkit and fixed the issue.
