### ISSUE TITLE
Using filter augpipe got AssertionError

### ISSUE THREAD

**Issue by manaclan** [NVlabs/stylegan2-ada-pytorch#176]
**Describe the bug**
I'm training conditional network with my custom dataset, everything was fine until it reached 50 ticks and return  
`AssertionError: Generator.synthesis.b64.torgb.affine.weight`   
This behavior doesn't exist when I use the default --augpipe
**To Reproduce**
1. `./docker_run.sh python train.py --outdir=./runs --data=./data/train2 \
--gpus=2 --cond 1  --mirror=1 --snap 50 --batch 8 --gamma 0.1 --augpipe bgcf`  

**Expected behavior**
Program terminated with `AssertionError: Generator.synthesis.b64.torgb.affine.weight`
Full stack trace:  
```
-- Process 1 terminated with the following error:                                                                          
Traceback (most recent call last):                                                                                            
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap                               
fn(i, *args)                                                                                                            
  File "/scratch/train.py", line 383, in subprocess_fn                                                                      
    training_loop.training_loop(rank=rank, **args)                                                                          
  File "/scratch/training/training_loop.py", line 360, in training_loop                                                         misc.check_ddp_consistency(module, ignore_regex=r'.*\.w_avg')                                            
data/train2 \    
  File "/scratch/torch_utils/misc.py", line 187, in check_ddp_consistency                                                   
    assert (nan_to_num(tensor) == nan_to_num(other)).all(), fullname                                                        
AssertionError: Generator.synthesis.b64.torgb.affine.weight
```

**Desktop :**
 - OS: Ubuntu 18.04
 - PyTorch version 1.7.1
 - CUDA toolkit version CUDA 11.2
 - NVIDIA driver version 460.32.03
 - GPU 2 x RTX 2080Ti
 - Docker:nvcr.io/nvidia/pytorch:20.12-py3

**Comment by manaclan** [comment]
tried pytorch 1.8.0 and cuda 11.1 and the problem solved
