### ISSUE TITLE
"bias_act_plugin", "upfirdn2d_plugin" problem

### ISSUE THREAD

**Issue by hello3196** [NVlabs/stylegan2-ada-pytorch#212]
I'm trying to train a stylegan2-ada model from scratch but then this error outputs.

I ran the command
CUDA_VISIBLE_DEVICES=4 python train.py --outdir=~/training-runs --data=../../../st1/dataset/coco_stuff_2017

Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
/home/jaewoong/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference
implementation. Details:

Traceback (most recent call last):
  File "/home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/jaewoong/anaconda3/envs/ss/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jaewoong/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py", line 48, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "/home/jaewoong/stylegan2-ada-pytorch/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 986, in load
    return _jit_compile(
  File "/home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1193, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1297, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e

RuntimeError: Error building extension 'bias_act_plugin': [1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSIO
N_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jaewoong/anaconda3/envs/ss/lib/py
thon3.8/site-packages/torch/include -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /hom
e/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/TH -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/includ
e/THC -isystem /usr/local/cuda/include -isystem /home/jaewoong/anaconda3/envs/ss/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -
D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --use_fa
st_math -std=c++14 -c /home/jaewoong/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cu -o bias_act.cuda.o
FAILED: bias_act.cuda.o
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/TH -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/jaewoong/anaconda3/envs/ss/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --use_fast_math -std=c++14 -c /home/jaewoong/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cu -o bias_act.cuda.o
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits,_Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/incl’e/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIt                                                                ‘
erator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits’asic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _I                                                               ‘
nIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/’bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIte                                                               ‘
rator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic’tring                                                                 ‘
<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6688:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable                                                                                    ‘
() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
       __p->_M_set_sharable();
       ~~~~~~~~~^~
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits,_
Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/incl’e/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIt                                                                ‘
erator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits’asic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _I                                                               ‘
nIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/’bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIte                                                               ‘
rator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic’tring                                                                 ‘
<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable                                                                                    ‘
() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
[2/3] c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/TH -isystem /home/jaewoong/anaconda3/envs/ss/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/jaewoong/anaconda3/envs/ss/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/jaewoong/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp -o bias_act.o
ninja: build stopped: subcommand failed.


The error does not end here and keeps on going but I aborted the command.



**Desktop (please complete the following information):**
 - OS: Linux
 - python: 3.8.12
 - pytorch 1.7.1
 - cudatoolkit 11.0
 - NVIDIA driver version: 450.80.02
 - GPU: RTX 2080
 - Docker: did you use Docker? No
 - ninja: 1.10.2

Thank you.

**Comment by forgotton-wind** [comment]
Maybe you can try to install a lower version of gcc(like 7.3.0).

**Comment by KryptixOne** [comment]
Not sure how relevant to Linux but in windows:
"subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1"
 Occured for me when I didn't have the LIB and LIBPATH environment variable created. 
Created them and set both to:
C:\Users\UserName\AppData\Local\Programs\Python\Python38\libs\

**Comment by choulishuhsu** [comment]
hello,do you fix it? i met the same problem
