### ISSUE TITLE
ImportError: No module named *_plugin...

### ISSUE THREAD

**Issue by wwt123-star** [NVlabs/stylegan2-ada-pytorch#291]
When I run the train.py, it reports the ImportError of *_plugin. I had found the 'build.ninja'  generated in the 'bias_act_plugin' and 'upfirdn2d_plugin' files but no 'bias_act.o', 'bias_act.cuda.o' and 'bias_act_plugin.pyd'. How can I solve these issues?

**Comment by asmile201711360030** [comment]
i hava the same question

**Comment by howard-liang-B** [comment]
I got this problem too

-------------------------------------------------------------------
warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1560, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/usr/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'upfirdn2d_plugin'
_____________________________________________________________________________

**Comment by HuangCaichen** [comment]
> I got this problem too
> 
> warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc()) Setting up PyTorch plugin "upfirdn2d_plugin"... Failed! /content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:
> 
> Traceback (most recent call last): File "/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py", line 32, in _init _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math']) File "/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/custom_ops.py", line 110, in get_plugin torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs) File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 997, in load keep_intermediates=keep_intermediates) File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1213, in _jit_compile return _import_module_from_library(name, build_directory, is_python_module) File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1560, in _import_module_from_library file, path, description = imp.find_module(module_name, [path]) File "/usr/lib/python3.7/imp.py", line 296, in find_module raise ImportError(_ERR_MSG.format(name), name=name) ImportError: No module named 'upfirdn2d_plugin'

have you solved it yet

**Comment by chengxuyuanabc** [comment]
> > 我也有这个问题
> > warnings.warn（'无法为 upfirdn2d 构建 CUDA 内核。回退到缓慢的引用实现。详情：\n\n' + traceback.format_exc（）） 设置 PyTorch 插件“upfirdn2d_plugin”...失败！/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py：34：UserWarning：无法为 upfirdn2d 构建 CUDA 内核。回退到缓慢的引用实现。详：
> > 回溯（最近一次调用最后）：文件“/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py”，第 32 行，_init _plugin = custom_ops.get_plugin（'upfirdn2d_plugin'， sources=sources， extra_cuda_cflags=['--use_fast_math']） 文件“/content/drive/MyDrive/StyleGAN/stylegan2-ada-pytorch/torch_utils/custom_ops.py”，第 110 行，在 get_plugin torch.utils.cpp_extension.load（name=module_name， verbose=verbose_build， sources=sources， **build_kwargs） 文件“/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py”，第 997 行，加载 keep_intermediates=keep_intermediates） 文件“/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py”，第 1213 行，_jit_compile 返回 _import_module_from_library（name， build_directory， is_python_module） 文件“/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py”， 第 1560 行，在_import_module_from_library 文件中，路径，描述 = imp.find_module（module_name， [路径]） 文件“/usr/lib/python3.7/imp.py”，第 296 行，find_module 引发 ImportError（_ERR_MSG.format（name）， name=name） ImportError： 没有名为 'upfirdn2d_plugin' 的模块
> 
> 你解决了吗

兄弟你解决了吗
