### ISSUE TITLE
Issue of upfirdn2d while training stylegan2

### ISSUE THREAD

**Issue by Anee115** [NVlabs/stylegan2-ada-pytorch#314]
**Describe the bug**
- OS: [Windows 11]
 - PyTorch torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 
 - CUDA toolkit version (e.g., CUDA 11.0)
 - GPU [RTX 4060]
okay, the issue comes while training. while training I had an issue with upfirdn2d.
initially, I was working with Cudatoolkit 12.3 version and Visual Studio Community 2022
but after one week's struggle I read the previous comments on this issue, Today I made a new env. from scratch with Python 3.7 changed my cuda from 12.1 to 11.0 and installed it in the system. I even changed the path to it and rebooted the system again, and then I changed the version of VS 2020 -VS 2019 community edition.  and then start the C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat file.Rebooted the system again. Then I reinstalled all the libs from scratch in my new environment. after that, I start training my file (train.py).
initially, it started working and created the parameters but then showed me error but after that when I moved toward the output directory I found 7 files.  
<img width="631" alt="Screenshot 2024-12-13 164102" src="https://github.com/user-attachments/assets/3ccb1c58-b4a4-4c3c-bbd1-ac9e8955d22b" />
but still I got a lot of errors of only this upfirdn2d.

Traceback (most recent call last):
  File "C:\WINDOWS\system32\temp\stylegan2-ada-pytorch\torch_utils\ops\upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "C:\WINDOWS\system32\temp\stylegan2-ada-pytorch\torch_utils\custom_ops.py", line 111, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "C:\Users\aneek\anaconda3\envs\video_gan_env\lib\site-packages\torch\utils\cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\aneek\anaconda3\envs\video_gan_env\lib\site-packages\torch\utils\cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\aneek\anaconda3\envs\video_gan_env\lib\site-packages\torch\utils\cpp_extension.py", line 1560, in _import_module_from_library.

**Screenshots**

<img width="813" alt="Screenshot 2024-12-13 163745" src="https://github.com/user-attachments/assets/26b94245-b97d-43dd-a448-10a4a4e41f6a" />

**Comment by halqadasi** [comment]
+1

**Comment by chengxuyuanabc** [comment]
> * GPU [RTX 4060]
> 
> <img alt="Screenshot 2024-12-13 163745" width="813" src="https://private-user-images.githubusercontent.com/191440005/395489628-26b94245-b97d-43dd-a448-10a4a4e41f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzNjQ2NzEsIm5iZiI6MTc1NDM2NDM3MSwicGF0aCI6Ii8xOTE0NDAwMDUvMzk1NDg5NjI4LTI2Yjk0MjQ1LWI5N2QtNDNkZC1hNDQ4LTEwYTRhNGU0MWY2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNVQwMzI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk4ZTQ4NDUyNmY1YjIxNzMzYmI1MzdhMTdkYjBjNDc2YWUyMzgzYmY0YTMyMGE5Y2Y2NTNjMjJjYTQ5ZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kvQ1HDu2wvbd8hO1HWHCxUuBOOoDz1EorhrGdwRFuto">

hi，do you fix it？

**Comment by zxg-zt** [comment]
Me too,do you fix it？

**Comment by Anee115** [comment]
Hi, I tried to fix it, but I couldn't.

**Comment by Bubble-water** [comment]
1. Clean PyTorch extension cache
rmdir /s /q "%LOCALAPPDATA%\torch_extensions"

2. Use VS2019 toolset in VS2022 environment (VS2022 includes VS2019 toolset when MSVC v142 is selected during installation)
Open "x64 Native Tools Command Prompt for VS2022" as Administrator, then run the following to use VS2019:
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.29

If using a very low CUDA version, you can use the VS2017 version:
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.16

3. Use Python environment in terminal
Activate your virtual environment or run your Python environment in the terminal to correctly compile the upfirdn2d_plugin CUDA code.
