### ISSUE TITLE
No module named 'upfirdn2d_plugin'

### ISSUE THREAD

**Issue by SBenkara** [NVlabs/stylegan2-ada-pytorch#37]
Hello,

When I start training, everything seems to work fine however I get the below message which does not interrupt the training

I am using Python 3.8, 
torch==1.7.0+cu110 torchvision==0.8.1+cu110 
and Cuda 11.0
my hardware is NVIDIA RTX 3090

```
No module named 'upfirdn2d_plugin'
  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + str(sys.exc_info()[1]))
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
C:\Users\VENUM\Google Drive\PyTorch\stylegan2-ada-pytorch\torch_utils\ops\upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:
```

**Comment by nurpax** [comment]
Please see https://github.com/NVlabs/stylegan2-ada-pytorch/issues/2#issuecomment-779457121

Please reopen this bug if you can’t find a solution from related GitHub issues.

**Comment by wwq-online** [comment]
I sovle this problem in ubuntu 16.04 by 
```bash
$ apt install ninja
```
this is my error log before i install ninjia
```
Loading training set...

Num images:  10106
Image shape: [3, 256, 256]
Label shape: [0]

Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
***//GAN/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "***//GAN/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py", line 48, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "***//GAN/stylegan2-ada-pytorch/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 969, in load
    return _jit_compile(
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1176, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1251, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1306, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
***//GAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "***//GAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "***//GAN/stylegan2-ada-pytorch/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 969, in load
    return _jit_compile(
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1176, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1251, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1306, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
***//GAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "***//GAN/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "***//GAN/stylegan2-ada-pytorch/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 969, in load
    return _jit_compile(
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1196, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/miniconda/envs/YOLOv5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1543, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/miniconda/envs/YOLOv5/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'upfirdn2d_plugin'

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
```
