### ISSUE TITLE
Errors related to the generated image

### ISSUE THREAD

**Issue by wry123456** [NVlabs/stylegan2-ada-pytorch#55]
The following error occurred when generating images with self-trained pkl files：
python generate.py --outdir outt --seeds 0-50 --network ./00005-data-auto2/network-snapshot-000600.pkl

Traceback (most recent call last):
  File "generate.py", line 127, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/mistgpu/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mistgpu/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mistgpu/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mistgpu/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mistgpu/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "generate.py", line 121, in generate_images
    PIL.Image.fromarray(img[0].cpu().numpy(), 'RGB').save(f'{outdir}/seed{seed:04d}.png')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2785, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2725, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2671, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 800, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data

What caused the above reasons？

**Comment by FwiffoSnork** [comment]
Is your pickle trained on greyscale or RGB images?

**Comment by wry123456** [comment]
> 您的泡菜是否经过了灰度或RGB图像训练？

thanks for your hints. My training set data is grayscale images, and I modified the way the images are saved in the generation code. It can be run.

**Comment by ramnoob** [comment]
@wry123456 
I would be very happy if you could share how to do this.

**Comment by whyydsforever** [comment]
> @wry123456 I would be very happy if you could share how to do this.
if your dataset is gratscale, you can delete the last dimesion of image by 
adding ` img = np.squeeze(img, axis=3)` in line 121
it will solve this problem

**Comment by clementdouarre** [comment]
FWIW, I also has to change the "RGB" string in the (original) line 121 to "L" for it to work.
