### ISSUE TITLE
RuntimeError: AssertionError:

### ISSUE THREAD

**Issue by mulkong** [NVlabs/stylegan2-ada-pytorch#9]
Hi. I'm trying to run the sample code but it raises an error. 

```
tick 0     kimg 0.0      time 1m 02s       sec/tick 15.7    sec/kimg 3923.85 maintenance 46.2   cpumem 3.91   gpumem 37.23  augment 0.000
Evaluating metrics...
Traceback (most recent call last):
  File "train.py", line 530, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 523, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 376, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/workspace/training/training_loop.py", line 371, in training_loop
    result_dict = metric_main.calc_metric(metric=metric, G=snapshot_data['G_ema'],
  File "/workspace/metrics/metric_main.py", line 45, in calc_metric
    results = _metric_dict[metric](opts)
  File "/workspace/metrics/metric_main.py", line 85, in fid50k_full
    fid = frechet_inception_distance.compute_fid(opts, max_real=None, num_gen=50000)
  File "/workspace/metrics/frechet_inception_distance.py", line 25, in compute_fid
    mu_real, sigma_real = metric_utils.compute_feature_stats_for_dataset(
  File "/workspace/metrics/metric_utils.py", line 216, in compute_feature_stats_for_dataset
    features = detector(images.to(opts.device), **detector_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 20, in forward
      pass
    else:
      ops.prim.RaiseException("AssertionError: ")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    if use_fp16:
      _4 = 5

Traceback of TorchScript, original code (most recent call last):
  File "c:\p4research\research\tkarras\dnn\gan3support\feature_detectors\inception.py", line 197, in forward
    def forward(self, img, return_features: bool = False, use_fp16: bool = False, no_output_bias: bool = False):
        batch_size, channels, height, width = img.shape # [NCHW]
        assert channels == 3
        ~~~~~~~~~~~~~~~~~~~~ <--- HERE

        # Cast to float.
RuntimeError: AssertionError:
```

Do you have any idea how to solve this problem? Thanks in advance

**Comment by nurpax** [comment]
Can you please post exact details about what you tried to run?  E.g., command line invocation, what dataset, software versions (CUDA and pytorch).

**Comment by mulkong** [comment]
The data I am using is 1 channel in gray scale. If you run it with (RGB)3 channels, it works, but if you run it with 1 channel, the above error occurs.

**Comment by nurpax** [comment]
I'd still like to get these specifics:

> Can you please post exact details about what you tried to run? E.g., command line invocation, what dataset, software versions (CUDA and pytorch), GPU.

Also: did you run your dataset through dataset_tool.py or just point training to a folder of images?  Dataset_tool.py does some error checking, and I'd like to know if that ran through to completion without errors.

**Comment by mulkong** [comment]
First, the details are as follows.

```
command line:python train.py --out_dir=./training-runs --data=./datasets/Xray.zip --gpu=2

dataset : X-ray (gray scale)
pytorch version: 1.8.0a0+1606899
CUDA: 11.1

```
Also, using the provided dataset_tool.py, I made a .zip file and proceeded. And it completed without error.

**Comment by nurpax** [comment]
It might be a grayscale related bug in metrics computation.  I haven't verified this on our side but i can check.

As a quick work-around, you could try training without metrics (add `--metrics none` option for train.py).  This way you could at least see if training works.

**Comment by mulkong** [comment]
Thank you. I've activated `--metrics none` and confirmed the learning process.

I wonder if the reason why it is learned after disabling automatic FID score calculation is because of the bug in metric calculation.

**Comment by nurpax** [comment]
I will leave this open.  There's a real bug in the code.
